### ISSUE TITLE
Pull request for update to MVC5 and AppVeyor

### ISSUE THREAD

**Issue by omarpiani** [jgauffin/griffin.mvccontrib#50]
Hi @jgauffin !
I successfully updated, compiled and runned and tested your project in my fork with VS2015, MVC5 and .NET Framework 4.5.2.

Admin backend at the moment have some issues caused by MVC3 template.

Project is forked here
https://github.com/omarpiani/griffin.mvccontrib

it will be awesome to use CI of appveyor for new releases of this package.
For example https://ci.appveyor.com/project/fiorebat/griffin-mvccontrib/build/1.0.5 builds, test requiring SQLExpress are failing, but I will replace them with LocalDB

Are you still available for an hot pull in this project?

Regards

**Comment by jgauffin** [comment]
yes. A pull request is most welcome.

**Comment by omarpiani** [comment]
PR was sent.
I suggest to setup this project in appveyor https://www.appveyor.com/ for CI! It's free for OpenSource and take few minutes

Add the SQLServer2014 service and place this Powershell configuration before build 
```
$startPath = $env:APPVEYOR_BUILD_FOLDER
$config = join-path $startPath "source\Griffin.MvcContrib.SqlServer.Tests\app.config"
$doc = (gc $config) -as [xml]
$doc.SelectSingleNode('//connectionStrings/add[@name="DefaultConnection"]').connectionString = 'Server=(local)\SQL2014;Database=GriffinMvcContribSQLTest;User ID=sa;Password=Password12!'
$doc.SelectSingleNode('//connectionStrings/add[@name="SetupConnection"]').connectionString = 'Server=(local)\SQL2014;Database=master;User ID=sa;Password=Password12!'
$doc.Save($config)

cd source
nuget restore
```

Next step can be AppVeyor can help you to publish new version of nuget packages, never tried, but seems fantastic

**Comment by jgauffin** [comment]
thank you
